### ISSUE TITLE
QR code is not show me 

### ISSUE THREAD

**Issue by Paresh-Maheshwari** [Santosl2/wpp-chatgpt#2]
i run command but qr code is not show me 
![image](https://user-images.githubusercontent.com/70533309/216751565-01564c52-0c9e-4bd9-976e-071b252367a7.png)

**Comment by Santosl2** [comment]
Hello there. Can you try in another terminal?

**Comment by vavidoa** [comment]
same for me, does not show the QR.
already tried in other terminals, and also with admin perms.

**Comment by Santosl2** [comment]
> same for me, does not show the QR. already tried in other terminals, and also with admin perms.

What's the Node JS version are you using?

**Comment by vavidoa** [comment]
Ok, solved

changed file "package.json"
    "@open-wa/wa-automate": "^4.55.0",

and run again npm install

and now is working

**Comment by Santosl2** [comment]
What did you change? Because the version is the same as the project's.

**Comment by vavidoa** [comment]
somehow previously the version downloaded was the "2.0.15"

**Comment by Santosl2** [comment]
I upgraded the package version, but i think it might be a bug in npm or Yarn. Thx dude
