### ISSUE TITLE
i given correct api but it showing incorrect api

### ISSUE THREAD

**Issue by mhdashikofficial** [Santosl2/wpp-chatgpt#3]
data: {
      error: {
        message: 'Incorrect API key provided: sk-CmlKF***************************************jP2n. You can find your API key at https://platform.openai.com/account/api-keys.',
        type: 'invalid_request_error',
        param: null,
        code: 'invalid_api_key'
      }

**Comment by Santosl2** [comment]
I believe you have solved this. If not create a new issue.
